### ISSUE TITLE
Week 3: Algorithmic Final

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/Data-Structures#5]
Score: **9/10**

[Video playlist](https://youtube.com/playlist?list=PLr8BhChjy1aTR7V3eznMVnltEJ7HooxpU)

### Individual Coding

[Documentation video (first 3 items)](https://youtu.be/f5dWvbXfHn0)

- [ ] Github Pages showing insights into Tech Talk concepts
- [ ] Commits on Github
- [ ] Code running on Replit and IntelliJ
- [ ] [Week 0 Menu](https://youtu.be/OMY2JYJQFQs) (runtime, organization, code + comments)
- [ ] [Week 1 Lists and Loops](https://youtu.be/JKaRYP42zDs) (runtime, organization, code + comments)
- [ ] [Week 2 Python Classes](https://youtu.be/NBVjlsYO6Ec) (runtime, organization, code + comments)

### Crossover Coding ([Video here](https://youtu.be/0TdDvM4-448))

- [ ] Show commits in partner's Github and Replit runtime (my main tasks were GH pages, math, swap, and fibonacci functions)

**Comment by AadyaDaita** [comment]
### 9/10
**Individual Coding:**

- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [x] GitHub commits you have made, show GitHub insights into your code commits.
- [x] Show Code running on Replit as well as IntelliJ
- [ ] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments **0.5 for the menu not being organized for the user: still organized by weeks**
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments

**Show Crossover contribution**:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo - **0.25 for not showing contributions to the crossover github page. Even though there were 12 commits, I hoped that you would add more technical to the project**
**Show anything you have done to enhance what you have learned from Python code** - **-0.25 I wish you added more technical, and perhaps something you learned over the trimester, instead of just fixing up crossover code**
